x-defaults: &default-opts
  tty: true
  privileged: true
  ports:
    - "8050:8050"
  volumes:
    - ./log:/app/log  # optional
    - ./db:/app/db # Should have to save database / settings
    - ./output:/app/videos # Must have to access videos
services:

# App
  GoRecord:
    <<: *default-opts
    container_name: Go-Record-WebUI
    image:  docker.io/lunanightbyte/gorecord:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.run 


# BUILD
# Core dependencies
  dev: 
    <<: *default-opts
    image:  docker.io/lunanightbyte/gorecord-base:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.base 

    volumes:
      - ./:/app # We use the entire workdir for development.
    tty: true
    privileged: true
