FROM alpine:latest AS final

# Install yt-dlp and Python dependencies
RUN apk add --no-cache yt-dlp python3

WORKDIR /app

COPY --from=lunanightbyte/gorecord-base:latest /compiled/server ./server
 
COPY ./settings /app/settings
# Expose the port the server listens on
EXPOSE 80

CMD ["./server"]
